name       : kdevelop
version    : 5.3.2
release    : 18
source     :
    - https://cdn.download.kde.org/stable/kdevelop/5.3.2/src/kdevelop-5.3.2.tar.xz : 08ccd575514187dcbd01ac976a619803410c26bdfabf5d2d5fd52c95b76d6f2a
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.ide
libsplit   : no
summary    : KDevelop IDE and Platform
description: |
    C++ IDE using KDE technologies based on KDevelop Platform.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WebEngine)
    - extra-cmake-modules
    - cppcheck
    - grantlee-devel
    - karchive-devel
    - kcmutils-devel
    - kconfig-devel
    - kcrash-devel
    - kdeclarative-devel
    - kdevelop-pg-qt-devel
    - kdoctools-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - ki18n-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kparts-devel
    - krunner-devel
    - kservice-devel
    - ktexteditor-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libboost-devel
    - libkomparediff2-devel
    - libksysguard-devel
    - llvm-clang-devel
    - okteta-devel
    - plasma-framework-devel
    - purpose-devel
    - shared-mime-info
    - sonnet-devel
    - subversion-devel
    - threadweaver-devel
rundeps    :
    - cppcheck
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
