name       : kdevelop
version    : 23.04.0
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.0/src/kdevelop-23.04.0.tar.xz : 8d1fd187ec68bdf2e2ff3432e421141b1256bb1bb7ba4a328065013c5abdb4d0
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.ide
summary    : KDevelop IDE and Platform
description: |
    C++ IDE using KDE technologies based on KDevelop Platform.
libsplit   : no
clang      : yes
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - cppcheck
    - grantlee-devel
    - karchive-devel
    - kcmutils-devel
    - kcrash-devel
    - kdeclarative-devel
    - kdevelop-pg-qt-devel
    - kdoctools-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - krunner-devel
    - ktexteditor-devel
    - libboost-devel
    - libkomparediff2-devel
    - libksysguard-devel
    - llvm-clang-devel
    - okteta-devel
    - purpose-devel
    - subversion-devel
    - threadweaver-devel
rundeps    :
    - cppcheck
    - devel :
        - threadweaver-devel
setup      : |
    # ld: clang_getCursorLocation: invalid version 3 (max 0), error adding symbols, bad value.
    %patch -p1 -R < $pkgfiles/a2155773002e544322b44964bcf1012ff15580d8.patch
    %patch -p1 -R < $pkgfiles/cb362b799f07b1d73c3674cb380bddec1ee2a600.patch
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache

    # Remove HTML docs
    rm -r $installdir/usr/share/doc
