name       : kdevelop
version    : 5.1.2
release    : 5
source     :
    - https://download.kde.org/stable/kdevelop/5.1.2/src/kdevelop-5.1.2.tar.xz : af54e807847d145fe5f3eb55962ed0d22e6363c2bc6c32167e51ca4823c00ac7
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : programming.ide
libsplit   : no
summary    : KDevelop IDE and Platform
description: |
    C++ IDE using KDE technologies based on KDevelop Platform.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5Quick)
    - cppcheck
    - extra-cmake-modules
    - kconfig-devel
    - kcrash-devel
    - kdeclarative-devel
    - kdevelop-pg-qt-devel
    - kdevplatform-devel
    - kdoctools-devel
    - kiconthemes-devel
    - ki18n-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - kcmutils-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - kparts-devel
    - krunner-devel
    - kservice-devel
    - ktexteditor-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libksysguard-devel
    - llvm-clang-devel
    - okteta-devel
    - plasma-framework-devel
    - shared-mime-info
    - threadweaver-devel
rundeps    :
    - cppcheck
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
