name       : kdevelop
version    : 5.2.4
release    : 14
source     :
    - https://cdn.download.kde.org/stable/kdevelop/5.2.4/src/kdevelop-5.2.4.tar.xz : 2c3ee424da6b0df06bea48db28abb9a00be9601a5494f026f9cbe704edd173c9
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : programming.ide
libsplit   : no
summary    : KDevelop IDE and Platform
description: |
    C++ IDE using KDE technologies based on KDevelop Platform.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5WebEngine)
    - cppcheck
    - extra-cmake-modules
    - grantlee-devel
    - karchive-devel
    - kcmutils-devel
    - kconfig-devel
    - kcrash-devel
    - kdeclarative-devel
    - kdevelop-pg-qt-devel
    - kdoctools-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - ki18n-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifications-devel
    - knotifyconfig-devel
    - kparts-devel
    - krunner-devel
    - kservice-devel
    - ktexteditor-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libboost-devel
    - libkomparediff2-devel
    - libksysguard-devel
    - llvm-clang-devel
    - okteta-devel
    - plasma-framework-devel
    - purpose-devel
    - shared-mime-info
    - sonnet-devel
    - subversion-devel
    - threadweaver-devel
rundeps    :
    - cppcheck
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
