name       : kdevelop
version    : 5.6.2
release    : 37
source     :
    - https://cdn.download.kde.org/stable/kdevelop/5.6.2/src/kdevelop-5.6.2.tar.xz : 0f86bc3fe53f761c1e3e3f7544577a0c41433be8bff310cf2e729f76f4363bf6
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.ide
summary    : KDevelop IDE and Platform
description: |
    C++ IDE using KDE technologies based on KDevelop Platform.
libsplit   : no
builddeps  :
    - pkgconfig(Qt5WebEngine)
    - cppcheck
    - grantlee-devel
    - karchive-devel
    - kcmutils-devel
    - kcrash-devel
    - kdeclarative-devel
    - kdevelop-pg-qt-devel
    - kdoctools-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - kitemmodels-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - krunner-devel
    - ktexteditor-devel
    - libboost-devel
    - libkomparediff2-devel
    - libksysguard-devel
    - llvm-clang-devel
    - okteta-devel
    - purpose-devel
    - subversion-devel
    - threadweaver-devel
rundeps    :
    - cppcheck
    - devel :
        - threadweaver-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache

    # Remove HTML docs
    rm -r $installdir/usr/share/doc
