name       : kdevelop
version    : 5.1.0
release    : 1
source     :
    - https://download.kde.org/stable/kdevelop/5.1.0/src/kdevelop-5.1.0.tar.xz : c0bc424a765a9be3ffb25acefcfa4db323b0612bae762fca1ae70225fa5c8ce8
license    :
    - GFDL-1.2
    - GPL-2.0
    - LGPL-2.1
component  : programming.ide
summary    : KDevelop IDE and Platform
description: |
    C++ IDE using KDE technologies based on KDevelop Platform.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5Quick)
    - clang-devel
    - extra-cmake-modules
    - kconfig-devel
    - kcrash-devel
    - kdeclarative-devel
    - kdevelop-pg-qt-devel
    - kdevplatform-devel
    - kdoctools-devel
    - kiconthemes-devel
    - ki18n-devel
    - kitemmodels-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - kcmutils-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - kparts-devel
    - krunner-devel
    - kservice-devel
    - ktexteditor-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - libksysguard-devel
    - okteta-devel
    - plasma-framework-devel
    - shared-mime-info
    - threadweaver-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
